### ISSUE TITLE
[User Story] (1) BLE Configuration

### ISSUE THREAD

**Issue by Shiv2205** [Shiv2205/SOEN_422_Final_Project#2]
As a professor I want to be able to configure the Smart Attendance device using bluetooth. 

### Acceptance criteria:
----------------------------------------------------
 - User is able to configure the device using a mobile app which has a BLE terminal.

### Task Breakdown:
 ---------------------------------------------------
- [x] **In configuration mode** (all status LEDs blinking) 
- [x] Make device discoverable through BLE.
- [x] Prompt user for wifi details.
- [x] Setup Professor Authentication routine (RFID Card Tap) upon successful wifi connection.
- [x] List all courses taught by Professor for selection.
- [x] Once course is selected, change operating mode from configuration to **running** (change status light to green).

**Comment by Shiv2205** [comment]
Commit 2cff053 allows the user to connect to the ESP32 and send commands via a BLE terminal app on the user's phone.

**Comment by Shiv2205** [comment]
Commit 9c06f58 allows the user to configure the wifi SSID which the ESP32 should connect to, and also allows the user to set the password. Wifi connection persists even when bluetooth client is disconnected.

**Comment by Shiv2205** [comment]
Commit d364018 will retrieve user information from backend when RFID card is scanned. If user is a professor, the courses associated with the latter will be sent to the device to display a menu. Upon selection of a course from the menu, bluetooth will be disconnected after 5 seconds.

**Comment by Shiv2205** [comment]
Commit b1db287 implements the status LEDs to display system state during runtime.

**Comment by Shiv2205** [comment]
User Story complete
